OdeToFood/src/OdeToFood/ViewComponents/GreetingViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Services;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class GreetingViewComponent : ViewComponent
    {
        private IGreeter _greeter;

        public GreetingViewComponent(IGreeter greeter)
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetGreeting();
            return View("Default", model);
        }
    }
}

OdeToFood/src/OdeToFood/ViewComponents/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

OdeToFood/src/OdeToFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <base href="/">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <enviroment names="Staging, Production">
        <link href="~/node_modules/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    </enviroment>
    <enviroment names="Development">
        <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    </enviroment>
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="/" class="navbar-brand">OdeToFood</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
                    <li><a href="Home/Search">Restautants</a></li>
                    <li><a href="Home/Map">Map</a></li>
                </ul>
                <div class="nav navbar-right">
                    @await Component.InvokeAsync("LoginLogout")
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
        <footer>
            @RenderSection("footer", false)
            @await Component.InvokeAsync("Greeting")
        </footer>
    </div>
    <!-- 1. Load libraries -->
    <!-- Polyfill(s) for older browsers -->
    <script src="~/libs/core-js/shim.min.js"></script>
    <script src="~/libs/zone.js/zone.js"></script>
    <script src="~/libs/reflect-metadata/Reflect.js"></script>
    <script src="~/libs/systemjs/system.src.js"></script>

    <!-- 2. Configure SystemJS -->
    <script src="~/systemjs.config.js"></script>
    <script>
        System.import('app').catch(function (err) { console.error(err); });
    </script>
</body>
</html>